Bf 001
danilo0391/baby-feed-management-service pull request #2
Opened 2023-10-31 22:27 UTC by danilo0391

-  Adicação das novas dependências do projeto;

- Criação do Model "Baby" + sua respectiva JPA;

**Obs**
-> Adicionei o file "application.properties" dentro do gitignore, mesmo assim ele subio para o repository. As info que estão lá são de outro DB que havia trabalho, somente para tirar o erro do JPA ao rodar a aplicação.

2023-11-03 19:55 UTC, gilbertopsantosjr requested changes

2023-11-03 19:55 UTC, gilbertopsantosjr commented on .gitignore
> +**/application.properties
this file belongs to the build , you shouldn't ignore it

2023-11-03 19:55 UTC, gilbertopsantosjr commented on src/main/java/com/babyfeed/managementservice/model/Baby.java
> +    private String name;
you may add validations here .. this is necessary to make sure you have consist data  
`@NotNull
  @Size(min = 3, max = 150)
  @Column(name = "sys_name", nullable = false, length = 150)
  private String name;
`

2023-11-03 19:55 UTC, gilbertopsantosjr commented on src/main/java/com/babyfeed/managementservice/model/Baby.java
> +    private Date dateOfBirth;
prefer to use LocalDateTime from java 8 , you have more features on this class Date is just too old 

`@Generated(GenerationTime.ALWAYS)
  private LocalDateTime updatedTime;`

2023-11-07 21:15 UTC, danilo0391 commented on .gitignore
> +**/application.properties
Done

2023-11-14 22:28 UTC, closed without merging